---
name: ci
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "feature/*" ]

permissions:
  contents: read

jobs:
  test:
    services:
      db:
        image: postgres:16
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest

    steps:
      - name: fetch source
        uses: actions/checkout@v4

      - name: setup compilers
        uses: erlef/setup-beam@v1
        with:
          otp-version: 26.x
          elixir-version: 1.16.x

      - name: cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ hashFiles('mix.*') }}

      - name: fetch dependencies
        run: mix deps.get --all

      - name: compile
        run: make build

      - name: run linters
        run: make lint

      - name: run tests
        run: make test
