---
name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 26.x
          elixir-version: 1.16.x
      - uses: actions/cache@v3
        env:
          cache-name: cache-elixir-deps
          with:
            path: deps
            key: ${{ runner.os }}-mix-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
            restore-keys: |
              ${{ runner.os }}-mix-${{ env.cache-name }}-
      - uses: actions/cache@v3
        env:
          cache-name: cache-compiled-build
        with:
          path: _build
          key: ${{ runner.os }}-mix-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ env.cache-name }}-
            ${{ runner.os }}-mix-
      - run: mix deps.get
      - run: mix do format --check-formatted, dialyzer
      - run: mix credo --strict
      - run: mix test
