---
name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 26.x
          elixir-version: 1.16.x
      - run: mix deps.get
      - run: mix test
